Commit Hash in Docker Image
deephaven/deephaven-server-docker pull request #115
Opened 2024-08-13 03:47 UTC by stanbrub

- Added the _deephaven-core_ SHA the `build-ci.yml` and `edge-ci.yml` workflows
- Used COMMIT_HASH in _server_ and _server-slim_ contexts and hcls
- Tested Branch CI on my fork.  Commit hash appears in manifest:
  - ex `docker container inspect ddb093257e90` shows output that contains
  - `"org.opencontainers.image.revision": "71646c35b2987e83cf34b53b632498b8aba21332"`
- Only _server_ and _server-slim_ were changed.  Do we need any more?
- Release CI was not touched (I did come up with a possible way.)
  - ex. `curl https://api.github.com/repos/deephaven/deephaven-core/commits/v0.35.0 | grep '"sha":' | head -1 | cut -d'"' -f4`

2024-08-13 16:49 UTC, stanbrub commented on server.hcl
> +}
We could use `curl https://api.github.com/repos/deephaven/deephaven-core/commits/v0.35.0 | grep '"sha":' | head -1 | cut -d'"' -f4` to grab the commit from the release and pass it into the image bake.  (A release-ci workflow triggered by "main" would not have it set.)

2024-08-13 17:20 UTC, devinrsmith commented on .github/workflows/edge-ci.yml
> +          echo "COMMIT_HASH="$(git rev-parse HEAD) >> $GITHUB_OUTPUT
We need to do the same sort of change here to separate job, variable name, etc.

2024-08-13 17:20 UTC, devinrsmith commented on contexts/server-slim/Dockerfile
> +ARG COMMIT_HASH
Don't think we need this globally, only for relevant stages.

2024-08-13 17:20 UTC, devinrsmith commented on server-slim.hcl
> +variable "COMMIT_HASH" {
We should change this to GIT_REVISION as well.

2024-08-13 22:25 UTC, devinrsmith requested changes
I think to move this label should only apply to edge / branch builds (using the Dockerfile split staging construct mentioned earlier). Also, does everything work if GIT_REVISION is set to an empty string instead of `"not-set"`?

2024-08-13 22:36 UTC, devinrsmith commented
Also, for the release, we probably technically want to point to the tag revision and not the commit revision, if we _were_ to add the LABEL for the release. I could probably argue we should use the tag name (as opposed to the revision SHA) for the GIT_REVISION for release images, but regardless, we would want to do that separately from this PR.

```
$ git rev-parse v0.35.0     
33d520aef42bc92d22bd5190511dbc6b67f87043

$ git rev-parse release/v0.35.0
d7a2af575e3dfbbc2c429c546c66e783c93358a5
```

Note the difference.

2024-08-19 23:28 UTC, stanbrub commented on server.hcl
> +}
I reworked it to do deephaven-bits-released and deephaven-bits-custom.  The branch-ci and edge-ci work on my fork.  Git revision shows up for server and server-slim.  For example, with `docker container inspect <container-id> | grep revision`, you get something like `"org.opencontainers.image.revision": "b5cae98c2f11b032cdd1b9c248dc5b4a0f95314a"`.  If the GIT_REVISION ARG is not pass in, you get `"org.opencontainers.image.revision": ""`

2024-08-20 00:11 UTC, devinrsmith approved these changes
LGTM. Please write a merge message describing this a bit more succinctly.

2024-08-20 01:53 UTC, merged